-- 1. HAPUS SEMUA TABEL LAMA (Urutan penting biar gak error foreign key)
DROP TABLE IF EXISTS DETAIL_PEMERIKSAAN CASCADE;
DROP TABLE IF EXISTS DETAIL_TAGIHAN CASCADE;
DROP TABLE IF EXISTS REKAM_MEDIS CASCADE;
DROP TABLE IF EXISTS PEMERIKSAAN CASCADE;
DROP TABLE IF EXISTS PERAWAT CASCADE;
DROP TABLE IF EXISTS DOKTER CASCADE;
DROP TABLE IF EXISTS LABORATORIUM CASCADE;
DROP TABLE IF EXISTS RAWAT_JALAN CASCADE;
DROP TABLE IF EXISTS RAWAT_INAP CASCADE;
DROP TABLE IF EXISTS TAGIHAN CASCADE;
DROP TABLE IF EXISTS TENAGA_MEDIS CASCADE;
DROP TABLE IF EXISTS LAYANAN CASCADE;
DROP TABLE IF EXISTS PASIEN CASCADE;
DROP TABLE IF EXISTS DEPARTEMEN CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;

-- 2. BUAT TABEL UTAMA
CREATE TABLE DEPARTEMEN (
    ID_Departemen CHAR(10) PRIMARY KEY,
    Nama_Departemen VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE PASIEN (
    ID_Pasien CHAR(10) PRIMARY KEY,
    Nama VARCHAR(100) NOT NULL,
    Tanggal_Lahir DATE NOT NULL,
    Alamat VARCHAR(255) NOT NULL,
    Nomor_Telepon VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE LAYANAN (
    ID_Layanan CHAR(10) PRIMARY KEY,
    Nama_Layanan VARCHAR(100) NOT NULL UNIQUE,
    Tarif_Dasar DECIMAL(10, 2) NOT NULL
);

CREATE TABLE TENAGA_MEDIS (
    ID_Tenaga_Medis CHAR(10) PRIMARY KEY,
    Nama_Tenaga_Medis VARCHAR(100) NOT NULL,
    ID_Departemen CHAR(10),
    FOREIGN KEY (ID_Departemen) REFERENCES DEPARTEMEN(ID_Departemen)
);

-- 3. BUAT TABEL TRANSAKSI
CREATE TABLE TAGIHAN (
    ID_Tagihan CHAR(10) PRIMARY KEY,
    ID_Pasien CHAR(10) NOT NULL, 
    Tanggal_Tagihan DATE NOT NULL,
    Total_Biaya DECIMAL(10, 2) NOT NULL,
    Status_Pembayaran VARCHAR(20) NOT NULL CHECK (Status_Pembayaran IN ('Belum Lunas', 'Lunas', 'Dicicil')),
    FOREIGN KEY (ID_Pasien) REFERENCES PASIEN(ID_Pasien) ON DELETE CASCADE
);

CREATE TABLE RAWAT_INAP (
    ID_Kamar CHAR(10) PRIMARY KEY,
    ID_Layanan CHAR(10) NOT NULL, 
    ID_Pasien CHAR(10) NOT NULL, -- PENTING: Kolom ini wajib ada!
    Tanggal_Masuk DATE NOT NULL,
    Tanggal_Keluar DATE,
    FOREIGN KEY (ID_Layanan) REFERENCES LAYANAN(ID_Layanan),
    FOREIGN KEY (ID_Pasien) REFERENCES PASIEN(ID_Pasien) ON DELETE cascade,
    CHECK (Tanggal_Keluar IS NULL OR Tanggal_Keluar >= Tanggal_Masuk)
);

CREATE TABLE RAWAT_JALAN (
    ID_Poli CHAR(10) PRIMARY KEY,
    ID_Layanan CHAR(10) NOT NULL,
    FOREIGN KEY (ID_Layanan) REFERENCES LAYANAN(ID_Layanan)
);

CREATE TABLE DOKTER (
    ID_Tenaga_Medis CHAR(10) PRIMARY KEY,
    Spesialisasi VARCHAR(100) NOT NULL,
    FOREIGN KEY (ID_Tenaga_Medis) REFERENCES TENAGA_MEDIS(ID_Tenaga_Medis) ON DELETE CASCADE
);

CREATE TABLE PERAWAT (
    ID_Tenaga_Medis CHAR(10) PRIMARY KEY,
    Shift VARCHAR(100) NOT NULL,
    FOREIGN KEY (ID_Tenaga_Medis) REFERENCES TENAGA_MEDIS(ID_Tenaga_Medis) ON DELETE CASCADE
);

CREATE TABLE REKAM_MEDIS (
    ID_Rekam_Medis CHAR(10) PRIMARY KEY,
    ID_Pasien CHAR(10) NOT NULL, 
    ID_Tenaga_Medis CHAR(10) NOT NULL, 
    Tanggal_Catatan DATE NOT NULL, 
    Diagnosis VARCHAR(100) NOT NULL, 
    Hasil_Pemeriksaan VARCHAR(100) NOT NULL,
    ID_Poli CHAR(10), -- PENTING: Kolom ini wajib ada!
    FOREIGN KEY (ID_Pasien) REFERENCES PASIEN(ID_Pasien) ON DELETE CASCADE,
    FOREIGN KEY (ID_Tenaga_Medis) REFERENCES TENAGA_MEDIS(ID_Tenaga_Medis),
    FOREIGN KEY (ID_Poli) REFERENCES RAWAT_JALAN(ID_Poli)
);

CREATE TABLE DETAIL_TAGIHAN (
    ID_Tagihan CHAR(10),
    ID_Layanan CHAR(10),
    Jumlah INT NOT NULL, 
    Subtotal DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (ID_Tagihan, ID_Layanan),
    FOREIGN KEY (ID_Tagihan) REFERENCES TAGIHAN(ID_Tagihan) ON DELETE CASCADE,
    FOREIGN KEY (ID_Layanan) REFERENCES LAYANAN(ID_Layanan)
);

CREATE TABLE PEMERIKSAAN (
    ID_Pemeriksaan CHAR(10) PRIMARY KEY,
    ID_Pasien CHAR(10) NOT NULL, 
    ID_Tenaga_Medis CHAR(10) NOT NULL, 
    Tanggal_Pemeriksaan DATE NOT NULL,
    Waktu_Pemeriksaan TIME NOT NULL,
    Ruang_Pemeriksaan VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_Pasien) REFERENCES PASIEN(ID_Pasien) ON DELETE CASCADE,
    FOREIGN KEY (ID_Tenaga_Medis) REFERENCES TENAGA_MEDIS(ID_Tenaga_Medis)
);

CREATE TABLE DETAIL_PEMERIKSAAN (
    ID_Layanan CHAR(10),
    ID_Pemeriksaan CHAR(10),
    Konsultasi VARCHAR (100) NOT NULL,
    Suntik_Vitamin VARCHAR (100),
    PRIMARY KEY (ID_Layanan, ID_Pemeriksaan),
    FOREIGN KEY (ID_Layanan) REFERENCES LAYANAN(ID_Layanan),
    FOREIGN KEY (ID_Pemeriksaan) REFERENCES PEMERIKSAAN(ID_Pemeriksaan) ON DELETE CASCADE
);

CREATE TABLE USERS (
    id_user SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('admin', 'dokter', 'pasien')),
    id_pasien CHAR(10),
    id_tenaga_medis CHAR(10),
    FOREIGN KEY (id_pasien) REFERENCES PASIEN(ID_Pasien) ON DELETE CASCADE,
    FOREIGN KEY (id_tenaga_medis) REFERENCES TENAGA_MEDIS(ID_Tenaga_Medis) ON DELETE CASCADE
);

-- 4. INSERT DATA DUMMY (HATI-HATI URUTANNYA)
INSERT INTO DEPARTEMEN VALUES 
('D001', 'Poli Umum'), ('D002', 'Poli Gigi'), ('D003', 'Bedah');

INSERT INTO PASIEN VALUES 
('P001', 'Budi Santoso', '1990-05-15', 'Jakarta', '081234567890'),
('P002', 'Ani Wijaya', '1985-11-20', 'Bandung', '081234567891');

INSERT INTO LAYANAN VALUES 
('L001', 'Konsultasi Dokter Umum', 150000),
('L002', 'Tambal Gigi', 450000),
('L005', 'Kamar Rawat Inap Kelas 1', 800000),
('L006', 'Kamar VIP', 1500000);

INSERT INTO RAWAT_JALAN VALUES 
('P-UMUM', 'L001'), ('P-GIGI', 'L002');

INSERT INTO TENAGA_MEDIS VALUES 
('TM001', 'Dr. Anton', 'D001'), ('TM002', 'Dr. Bella', 'D002');
INSERT INTO DOKTER VALUES 
('TM001', 'Umum'), ('TM002', 'Gigi');

INSERT INTO USERS (username, password_hash, role, id_tenaga_medis) VALUES 
('admin', 'admin123', 'admin', NULL),
('dokter1', 'dokter123', 'dokter', 'TM001');